### ISSUE TITLE
Site looks great

### ISSUE THREAD

**Issue by hanieldanson-zz** [rgrewalucsb/rgrewalucsb.github.io#1]
I really like what you've done with your site since we last paired. It's definitely taken some positive steps forward, and I can tell you've learned a lot since building it originally. Also, I like that you took the time to make a polished looking game. I made a game as well, but it's not nearly as polished looking as yours. Great job man!

I have a few bits of constructive criticism, but it's mainly just me being OCD. My personal preference and what I've seen more of around the interwebs is to do hover over text color change as opposed to a background highlight. If you decide to stick with the background hover, I would recommend going with a more subtle color. I would say the same thing about the blog post titles and the images that get highlighted when hovering too. You may want to take the hover over off the images completely because it doesn't highlight at the same time as the blog post title. Like I said before, if you want to keep that stuff, then I would recommend making it more subtle (smaller radius around image or text) and changing the highlight color to something more shadowy like a light or dark grey.

Style is obviously not something we can measure objectively. Just my two cents and I hope it's helpful!

**Comment by rgrewalucsb** [comment]
Thanks a bunch for the feedback, I was also iffy about the box-shadow over the images so I took it off. I also made all the hover elements a bit more subtle of a color. Looks a lot better, thanks again.
